HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Models/Competency.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HomeWork_for_Present_Connection.Models
{

    
    public partial class Competency
    {
       
        public Competency()
        {
            this.CompetenceAssessments = new HashSet<CompetenceAssessment>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Kompetencija")]
        public string Name { get; set; }

        [Display(Name = "Kompetencijos aprasas")]
        public string Status { get; set; }

        public int OrganisationId { get; set; }
    
        
        public virtual ICollection<CompetenceAssessment> CompetenceAssessments { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Controllers/CompetenciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeWork_for_Present_Connection.Models;

namespace HomeWork_for_Present_Connection.Controllers
{
    public class CompetenciesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Competencies
        public ActionResult Index(int OrganisationId = 0)
        {
            var competencies = db.Competencies.Include(c => c.Organisation);
            //return View(competencies.ToList());

            //var competence = db.Competence.Include(c => c.User).Include(c => c.Competency);
            //var competenceAssessments = db.CompetenceAssessments.Include(c => c.User).Include(c => c.Competency);
            ViewBag.OrganisationId = new SelectList(db.Organisations, "Id", "Name");
            var competence = db.Competencies.Include(c => c.Organisation);
            if (OrganisationId > 0)
            {
                var model =
                    from r in db.Competencies
                    orderby r.Name
                    where r.Organisation.Id == OrganisationId //r.User.Organisation.Id == OrganisationId
                    select r;
                return View(model);
            }
            else
            {
                var model = db.Competencies.Include(c => c.Organisation);
                return View(model);
            }
        }

        // GET: Competencies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Competency competency = db.Competencies.Find(id);
            if (competency == null)
            {
                return HttpNotFound();
            }
            return View(competency);
        }

        // GET: Competencies/Create
        public ActionResult Create()
        {
            ViewBag.OrganisationId = new SelectList(db.Organisations, "Id", "Name");
            return View();
        }

        // POST: Competencies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Status,OrganisationId")] Competency competency)
        {
            if (ModelState.IsValid)
            {
                db.Competencies.Add(competency);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OrganisationId = new SelectList(db.Organisations, "Id", "Name", competency.OrganisationId);
            return View(competency);
        }

        // GET: Competencies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Competency competency = db.Competencies.Find(id);
            if (competency == null)
            {
                return HttpNotFound();
            }
            ViewBag.OrganisationId = new SelectList(db.Organisations, "Id", "Name", competency.OrganisationId);
            return View(competency);
        }

        // POST: Competencies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Status,OrganisationId")] Competency competency)
        {
            if (ModelState.IsValid)
            {
                db.Entry(competency).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OrganisationId = new SelectList(db.Organisations, "Id", "Name", competency.OrganisationId);
            return View(competency);
        }

        // GET: Competencies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Competency competency = db.Competencies.Find(id);
            if (competency == null)
            {
                return HttpNotFound();
            }
            return View(competency);
        }

        // POST: Competencies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Competency competency = db.Competencies.Find(id);
            db.Competencies.Remove(competency);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Views/Competencies/Create.cshtml
@model HomeWork_for_Present_Connection.Models.Competency

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    

    <div class="form-horizontal">
        <br/><br/>
        <div class="form-group">
            @Html.LabelFor(model => model.OrganisationId, "OrganisationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OrganisationId", null, "Pasirinkite Imone", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganisationId, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atgal", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Views/Competencies/Delete.cshtml
@model HomeWork_for_Present_Connection.Models.Competency

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Competency</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Organisation.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organisation.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Views/Competencies/Edit.cshtml
@model HomeWork_for_Present_Connection.Models.Competency

@{
    ViewBag.Title = "Edit";
}

<h2></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3><b>Imone</b></h3>
        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownList("OrganisationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganisationId, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atgal", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Views/Competencies/Index.cshtml
@model IEnumerable<HomeWork_for_Present_Connection.Models.Competency>

@{
    ViewBag.Title = "Kompetencija";
}

<form method="get">
    <p>
        <h3>Imones</h3>
        @Html.DropDownList("OrganisationId", null, "Pasirinkite Imone", htmlAttributes: new { @class = "form-control" })
        <input type="submit" value="filter" />
    </p>
    <br />
</form>

<h2>Kompetencija</h2>

<p>
    @Html.ActionLink("Ivesti nauja", "Create", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            <center>
                @Html.DisplayNameFor(model => model.Name)
            </center>
        </th>
 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <center>
                <a href="@Url.Action("Edit", "Competencies", new { id=item.Id })">
                    @Html.DisplayFor(modelItem => item.Name)
                </a>
            </center>
        </td>
   

    </tr>
}

</table>