HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Models/Organisation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace HomeWork_for_Present_Connection.Models
{
    
    
    public partial class Organisation
    {
        
        public Organisation()
        {
            this.Users = new HashSet<User>();
            this.Competencies = new HashSet<Competency>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Pavadinimas")]
        public string Name { get; set; }

        [Display(Name = "Aprasymas")]
        public string Description { get; set; }

        [Display(Name = "Statusas")]
        public string Status { get; set; }

        public int ParentID { get; set; }

        public DateTime CreationDate
        {
            get
            {
                return this.creationDate.HasValue
                    ? this.creationDate.Value
                    : DateTime.Now;
            }
            set
            {
                this.creationDate = value;
            }
        }
        private DateTime? creationDate = null;
    
        
        public virtual ICollection<User> Users { get; set; }
        
        public virtual ICollection<Competency> Competencies { get; set; }
    }
}

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Controllers/OrganisationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeWork_for_Present_Connection.Models;

namespace HomeWork_for_Present_Connection.Controllers
{
    public class OrganisationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Organisations
        public ActionResult Index()
        {

            return View(db.Organisations.ToList());
        }

        // GET: Organisations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organisation organisation = db.Organisations.Find(id);
            if (organisation == null)
            {
                return HttpNotFound();
            }
            return View(organisation);
        }

        // GET: Organisations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Organisations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Status,ParentID,CreationDate")] Organisation organisation)
        {
            if (ModelState.IsValid)
            {
                db.Organisations.Add(organisation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(organisation);
        }

        // GET: Organisations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organisation organisation = db.Organisations.Find(id);
            if (organisation == null)
            {
                return HttpNotFound();
            }
            return View(organisation);
        }

        // POST: Organisations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Status,ParentID,CreationDate")] Organisation organisation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organisation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(organisation);
        }

        // GET: Organisations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organisation organisation = db.Organisations.Find(id);
            if (organisation == null)
            {
                return HttpNotFound();
            }
            return View(organisation);
        }

        // POST: Organisations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Organisation organisation = db.Organisations.Find(id);
            db.Organisations.Remove(organisation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Views/Organisations/Create.cshtml
@model HomeWork_for_Present_Connection.Models.Organisation

@{
    ViewBag.Title = "Create";
}

<h2>Imone</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        

        

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atgal", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Views/Organisations/Delete.cshtml
@model HomeWork_for_Present_Connection.Models.Organisation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Organisation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Views/Organisations/Edit.cshtml
@model HomeWork_for_Present_Connection.Models.Organisation

@{
    ViewBag.Title = "Edit";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <br/>
        <h2>Imone</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        



                @Html.HiddenFor(model => model.ParentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
 


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<br/><br/>
<div>
    @Html.ActionLink("Atgal", "Index", null, new { @class = "btn btn-default" })
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWork_for_Present_Connection/HomeWork_for_Present_Connection/Views/Organisations/Index.cshtml
@model IEnumerable<HomeWork_for_Present_Connection.Models.Organisation>

@{
    ViewBag.Title = "Imones";
}

<h2>Imones</h2>

<p>
    @Html.ActionLink("Ivesti nauja", "Create", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            <center>
                @Html.DisplayNameFor(model => model.Name)
            </center>
        </th>
        <th>
            <center>
                <b>Darbuotoju skaicius</b>
            </center>
        </th>
        <th>
            <center>
                <b>Kompetenciju skaicius</b>
            </center>
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <center>
                <a href="@Url.Action("Edit", "Organisations", new { id=item.Id })">
                    @Html.DisplayFor(modelItem => item.Name)
                </a>
            </center>
        </td>
        <td>
            <center>

            </center>
        </td>
        <td>
            <center>
                
            </center>
        </td>
        
        
    </tr>
}

</table>